/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package generatedRecords;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AvroRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2669676612825429242L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroRecord\",\"namespace\":\"generatedRecords\",\"fields\":[{\"name\":\"TemperatureRecorded\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"TimeRecorded\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"Temperature\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroRecord> ENCODER =
      new BinaryMessageEncoder<AvroRecord>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroRecord> DECODER =
      new BinaryMessageDecoder<AvroRecord>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AvroRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AvroRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AvroRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroRecord>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AvroRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AvroRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AvroRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AvroRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String TemperatureRecorded;
  private java.lang.String TimeRecorded;
  private int Temperature;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroRecord() {}

  /**
   * All-args constructor.
   * @param TemperatureRecorded The new value for TemperatureRecorded
   * @param TimeRecorded The new value for TimeRecorded
   * @param Temperature The new value for Temperature
   */
  public AvroRecord(java.lang.String TemperatureRecorded, java.lang.String TimeRecorded, java.lang.Integer Temperature) {
    this.TemperatureRecorded = TemperatureRecorded;
    this.TimeRecorded = TimeRecorded;
    this.Temperature = Temperature;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return TemperatureRecorded;
    case 1: return TimeRecorded;
    case 2: return Temperature;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: TemperatureRecorded = value$ != null ? value$.toString() : null; break;
    case 1: TimeRecorded = value$ != null ? value$.toString() : null; break;
    case 2: Temperature = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'TemperatureRecorded' field.
   * @return The value of the 'TemperatureRecorded' field.
   */
  public java.lang.String getTemperatureRecorded() {
    return TemperatureRecorded;
  }



  /**
   * Gets the value of the 'TimeRecorded' field.
   * @return The value of the 'TimeRecorded' field.
   */
  public java.lang.String getTimeRecorded() {
    return TimeRecorded;
  }



  /**
   * Gets the value of the 'Temperature' field.
   * @return The value of the 'Temperature' field.
   */
  public int getTemperature() {
    return Temperature;
  }



  /**
   * Creates a new AvroRecord RecordBuilder.
   * @return A new AvroRecord RecordBuilder
   */
  public static generatedRecords.AvroRecord.Builder newBuilder() {
    return new generatedRecords.AvroRecord.Builder();
  }

  /**
   * Creates a new AvroRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroRecord RecordBuilder
   */
  public static generatedRecords.AvroRecord.Builder newBuilder(generatedRecords.AvroRecord.Builder other) {
    if (other == null) {
      return new generatedRecords.AvroRecord.Builder();
    } else {
      return new generatedRecords.AvroRecord.Builder(other);
    }
  }

  /**
   * Creates a new AvroRecord RecordBuilder by copying an existing AvroRecord instance.
   * @param other The existing instance to copy.
   * @return A new AvroRecord RecordBuilder
   */
  public static generatedRecords.AvroRecord.Builder newBuilder(generatedRecords.AvroRecord other) {
    if (other == null) {
      return new generatedRecords.AvroRecord.Builder();
    } else {
      return new generatedRecords.AvroRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for AvroRecord instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroRecord>
    implements org.apache.avro.data.RecordBuilder<AvroRecord> {

    private java.lang.String TemperatureRecorded;
    private java.lang.String TimeRecorded;
    private int Temperature;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(generatedRecords.AvroRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.TemperatureRecorded)) {
        this.TemperatureRecorded = data().deepCopy(fields()[0].schema(), other.TemperatureRecorded);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.TimeRecorded)) {
        this.TimeRecorded = data().deepCopy(fields()[1].schema(), other.TimeRecorded);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.Temperature)) {
        this.Temperature = data().deepCopy(fields()[2].schema(), other.Temperature);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing AvroRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(generatedRecords.AvroRecord other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.TemperatureRecorded)) {
        this.TemperatureRecorded = data().deepCopy(fields()[0].schema(), other.TemperatureRecorded);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.TimeRecorded)) {
        this.TimeRecorded = data().deepCopy(fields()[1].schema(), other.TimeRecorded);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Temperature)) {
        this.Temperature = data().deepCopy(fields()[2].schema(), other.Temperature);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'TemperatureRecorded' field.
      * @return The value.
      */
    public java.lang.String getTemperatureRecorded() {
      return TemperatureRecorded;
    }


    /**
      * Sets the value of the 'TemperatureRecorded' field.
      * @param value The value of 'TemperatureRecorded'.
      * @return This builder.
      */
    public generatedRecords.AvroRecord.Builder setTemperatureRecorded(java.lang.String value) {
      validate(fields()[0], value);
      this.TemperatureRecorded = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'TemperatureRecorded' field has been set.
      * @return True if the 'TemperatureRecorded' field has been set, false otherwise.
      */
    public boolean hasTemperatureRecorded() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'TemperatureRecorded' field.
      * @return This builder.
      */
    public generatedRecords.AvroRecord.Builder clearTemperatureRecorded() {
      TemperatureRecorded = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'TimeRecorded' field.
      * @return The value.
      */
    public java.lang.String getTimeRecorded() {
      return TimeRecorded;
    }


    /**
      * Sets the value of the 'TimeRecorded' field.
      * @param value The value of 'TimeRecorded'.
      * @return This builder.
      */
    public generatedRecords.AvroRecord.Builder setTimeRecorded(java.lang.String value) {
      validate(fields()[1], value);
      this.TimeRecorded = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'TimeRecorded' field has been set.
      * @return True if the 'TimeRecorded' field has been set, false otherwise.
      */
    public boolean hasTimeRecorded() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'TimeRecorded' field.
      * @return This builder.
      */
    public generatedRecords.AvroRecord.Builder clearTimeRecorded() {
      TimeRecorded = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'Temperature' field.
      * @return The value.
      */
    public int getTemperature() {
      return Temperature;
    }


    /**
      * Sets the value of the 'Temperature' field.
      * @param value The value of 'Temperature'.
      * @return This builder.
      */
    public generatedRecords.AvroRecord.Builder setTemperature(int value) {
      validate(fields()[2], value);
      this.Temperature = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'Temperature' field has been set.
      * @return True if the 'Temperature' field has been set, false otherwise.
      */
    public boolean hasTemperature() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'Temperature' field.
      * @return This builder.
      */
    public generatedRecords.AvroRecord.Builder clearTemperature() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroRecord build() {
      try {
        AvroRecord record = new AvroRecord();
        record.TemperatureRecorded = fieldSetFlags()[0] ? this.TemperatureRecorded : (java.lang.String) defaultValue(fields()[0]);
        record.TimeRecorded = fieldSetFlags()[1] ? this.TimeRecorded : (java.lang.String) defaultValue(fields()[1]);
        record.Temperature = fieldSetFlags()[2] ? this.Temperature : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroRecord>
    READER$ = (org.apache.avro.io.DatumReader<AvroRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.TemperatureRecorded);

    out.writeString(this.TimeRecorded);

    out.writeInt(this.Temperature);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.TemperatureRecorded = in.readString();

      this.TimeRecorded = in.readString();

      this.Temperature = in.readInt();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.TemperatureRecorded = in.readString();
          break;

        case 1:
          this.TimeRecorded = in.readString();
          break;

        case 2:
          this.Temperature = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










